packages/app/app/layout.tsx, packages/app/app/stacks/empty-state.tsx, packages/app/app/stacks/layout.tsx, packages/app/app/stacks/page.tsx, packages/app/app/stacks/table.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/package.json, packages/app/tailwind.config.js, yarn.lock
- add header with title and button
- add tabs with headless ui
- install @headlessui/tailwindcss plugin to be able to use "selected-ui:" helpers
- add layout page
- add mock stacks table
=> feat: add Your stacks header and tabs

packages/app/models/stack-order/stack-order.ts
**Description**
Fix error when opening a modal with cowOrders undefined
**Summary**
- add it to calculateStackAveragePrice and totalStackOrdersDone
**Error**
=> fix: condition got error when cowOrders was undefined

packages/app/components/OrdersProgressBar.tsx, packages/app/components/StacksTable.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stack-modal/StackProgress.tsx, packages/app/models/order/order.ts
**Description**
Progress bar should be based on cow orders and not on order slots, this was causing a bug of showing progress without orders.
**Screenshot**
=> fix: Progress bar should be based on cow orders and not on order slots

packages/app/components/SelectNetwork.tsx
**Description**
Fixes opening select network modal on mobile while with menu open
**previously**
**now**
=> fix: changing network on mobile when menu is open

packages/app/components/stackbox/Stackbox.tsx
- Add correct padding to Datepicker 
- add hover effect
comments: https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez
=> fix: add correct padding to datepicker button

packages/app/app/layout.tsx
**Description** 
Navbar should be full-width.
Fix:
- remove max width from layout
**previously**
**now**
comments:
https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez
=> fix: remove layout max-witdh

packages/app/components/token-picker/TokenPicker.tsx, packages/app/contexts/TokenListContext.tsx, packages/app/utils/token.ts
* Updated Modal logic to opt-out the background opacity
* Created the Toast component
* Updated UI page where we display Stackly components
3) Go to the Stackly homepage, connect your wallet, and then click any of the two "Select token" buttons
=> [STK-105][FEAT] - Display user's token balances

packages/app/components/stackbox/Stackbox.tsx
=> fix: do not allow negative numbers on input

packages/app/components/stackbox/Stackbox.tsx
When no `address` Stackbox  should show  Connect button
ps: the proper size of the button will be updated when #64 merges.
=> fix: when no address it Stackbox should show connect button

packages/app/components/DatePicker.tsx, packages/app/components/stackbox/Stackbox.tsx
fixes double border:
And remove outline when clicking the date
=> fix: extra border on end date input on desktop and outline

packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stackbox/ConfirmStackModal.tsx
Add ability to close this dialogs:
**on cancel**
**on create**
=> fix: add ability to close loading transaction Dialog

packages/app/components/stackbox/Stackbox.tsx
**description**
we should not allow the user to select the same token twice.
**Logic example**
if user selects a token A and Token A == Token B
- setTokenB(previousTokenA) 
- if doesn't have previousTokenA, it will be undefined which renders the "select token")
=> fix: add logic to  not enable to select the same token on both sides

packages/app/app/layout.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stack-modal/StackProgress.tsx, packages/app/components/token-picker/TokenPicker.tsx, packages/app/ui/buttons/base.ts, packages/app/ui/modal/ModalContent.tsx, packages/app/ui/modal/ModalFooter.tsx, packages/app/ui/modal/ModalHeader.tsx
**summary**
- add default color to body
- add lighter border color to "tertiary" button
- check modal padding x (24px)
- stack modal header padding y
- consistent padding inside Stack modal
**images**
=> fix: padding on StackModal, default color and more

packages/app/providers/wagmi-config.ts
Default `publicProvider` from wagmi isn't working on production. Changed to a custom RPC.
=> fix: update json provider

packages/app/components/DatePicker.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/public/assets/icons/index.tsx, packages/app/public/assets/icons/info.svg, packages/app/ui/icon/Icon.tsx
* [STK-141](https://linear.app/swaprhq/issue/STK-141/add-start-datetime-logic)
* [STK-137](https://linear.app/swaprhq/issue/STK-137/show-error-when-creating-stack-in-the-past)
* Check if the start date is 10m or less from now, if so, display an error
* Highlight date fields that are erroring
* Allow 1 date field error at the time
3) Go to the Stackly homepage, connect your wallet
4) The current date time should be displayed in the "start time" input.
4.1) If the user selects a date that is less than 10 minutes from the current time, an error should appear
4.2) If the user has both errors for start and end date, then only 1 error at the time should be displayed
=> [STK-141][FEAT] - Add start datetime logic

packages/app/models/stack-order/stack-order.ts
=> fix: Stack shows it has remaining funds when it has not

packages/app/hooks/autoConnect.ts, packages/app/providers/wagmi-config.ts
This PR aims to fix disconnecting issue that was introduced with auto connect.
Looks like it still works on Safe:
The connected wallet is the Safe wallet and not the user.
=> fix: safe autoconnect doesn't allow to disconnect

packages/app/components/DatePicker.tsx, packages/app/components/stackbox/Stackbox.tsx
* Overwrite selected StartTime for the Stackbox, if the date is in the past
https://www.loom.com/share/eb14ef3c7de54b6baf45368e31d80d8f?sid=bd8bd3ae-7a03-45ea-bb7a-7350b49f0643
3) Go to the Stackly homepage, connect your wallet
4) "Now" text should be displayed in the "Starting from" input.
5) If the user selects a date in the past, it will be overwritten into "Now"
=> [STK-175][FEAT] - Update Stackbox logic to forbid start time in the past

packages/app/app/layout.tsx, packages/app/components/navbar/MobileMenu.tsx, packages/app/constants/index.ts, packages/landing/next.config.js
- add stackly app and landing url links as constants to app
- add missing links on mobile menu
-  also remove unoptimized images from landing next config (needed for fleek on app but no need on landing.)
=> fix: add missing links to mobile mobile menu 

packages/app/components/token-picker/TokenPicker.tsx
=> fix: broken empty state on select token when address was filled

packages/app/providers/wagmi-config.ts
Removes safe from wallet connector
Still works on Safe app
=> fix: remove safe from connect wallet list

packages/app/components/stackbox/Stackbox.tsx
* Update "Stack Every" label in the Stackbox to display the "To receive" token symbol
* Added Stackbox label empty state (for no "To Receive" token selected)
3) Go to Stackly landing page
4) Connect your wallet
5) Play around selecting different tokens "To receive". Also try selecting and deselecting a strategy to check the empty state.
=> [SWA-189][FIX] - update Stackbox labels to reflect selected tokens info

packages/app/components/stackbox/ConfirmStackModal.tsx, packages/app/components/stackbox/Stackbox.tsx
On the preview stack I think "worth" is confusing. People asked me what it meant.
After discussing we decided to go with "swapping" as it tells what we do.
**now**
**before**
=> Update: Change words from "worth" -> "swapping" on preview stack

packages/app/components/ConnectButton.tsx
Update token balance to show wrapped version, since we don't allow using native tokens.
**Now**
=> update: show wrapped tokens instead of native tokens on account

packages/app/components/FathomAnalytics.tsx, packages/landing/components/FathomAnalytics.tsx
* Update the way we handle missing FA Site ID to stop the app from halting on dev envs when the FA site ID env var is missing
3) Go to Stackly dApp
4) It shouldn't throw an error if the FA Site ID env var is not set
=> [CHORE] - Change from Erroring to Console when fathom site ID is missing

packages/app/app/layout.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/tailwind.config.js, packages/app/ui/buttons/RadioButton.tsx
* Moved some code out from the Stackbox and into SelectNetwork (concern separation)
* Created custom code to handle the Chain switch as app state 
* Updated the way we consume the chain switch where it's needed
3) Go to Stackly dApp
4) Connect your wallet
5) 
a. The matrix background image should be both horizontally and vertically centered
b. The container for both date pickers should have the correct spacing for both mobile and desktop
=> [STK-188][STYLES] - Center dApp background image and update date pickers spacing

packages/app/components/ConnectButton.tsx, packages/app/components/SelectNetwork.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/components/strategies/Strategies.tsx, packages/app/components/strategies/StrategyCard.tsx, packages/app/components/token-picker/TokenPicker.tsx, packages/app/contexts/NetworkContext.tsx, packages/app/contexts/StackboxFormContext.tsx, packages/app/contexts/TokenListContext.tsx, packages/app/contexts/index.ts, packages/app/providers/Providers.tsx, packages/app/providers/index.ts, packages/app/providers/wagmi-config.ts, packages/app/utils/chain.ts, packages/app/utils/index.ts
* Moved some code out from the Stackbox and into SelectNetwork (concern separation)
* Created custom code to handle the Chain switch as app state 
* Updated the way we consume the chain switch where it's needed
3) Go to Stackly dApp
4) Connect your wallet
5) You should be able to change the selected chain either by connecting the wallet or with your wallet disconnected from the dApp. The Stackbox, Strategies, and TokenPicker should display relevant information either way.
=> [STK-209][FEAT] - Enable select network without a connected wallet

packages/app/components/stack-modal/StackOrdersTable.tsx
* Update the way we compute the executed order AVG price
**PRE-CONDITIONS:** You need to have existing stacks with executed orders in place to test this fix
3) Go to Stackly dApp
4) Connect your wallet
5) Go to "Your Stacks", choose one of them, and click "View Details"
6) When the Order Details modal opens up, the right-most column should have the correct token pair price
=> [STK-216][FIX] - Wrong AVG bought token price on executed orders table

packages/app/app/stacks/page.tsx, packages/app/app/stacks/stacksOrders.tsx, packages/app/components/ConnectButton.tsx, packages/app/components/SelectNetwork.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stackbox/ConfirmStackModal.tsx, packages/app/contexts/NetworkContext.tsx, packages/app/contexts/StackboxFormContext.tsx, packages/app/contexts/TokenListContext.tsx, packages/app/providers/Providers.tsx, packages/app/tsconfig.json, packages/app/utils/chain.ts
This PR was mainly refactoring NetworkProvider to fixe this issue: Trying to switch to Ethereum network not working.
https://gyazo.com/c1139b2d7775f7866004f86835016575
This breaks using Stackly on Safe wallet, cause on safe to access wallets is on network base. So to access on ethereum mainnet, you can't switch to gnosis and then back to Ethereum.
=> Fixes: Switching network not working properly

packages/app/app/stacks/stacksOrders.tsx
**Problem**
Looking into orders they are disorganised and it's hard to check on the past orders.
**Previously**
**Now**
**Previously**
**Now**
=> feat: sort stacks by start/end time

packages/app/components/stack-modal/StackProgress.tsx, packages/app/models/stack-order/stack-order.ts
Show estimated total stack when we do first order.
estimation function is:
`Stack amount / avg stack price`
Don't show when no orders or stack is complete.
preview:
=> Add estimated total stack

packages/subgraph/src/mappings/order.ts
Sometimes token name or symbol are missing from contract. This fix prevents that to break the subgraph and UI.
=> fix: missing token name and symbol on subgraph

packages/app/public/assets/blockchains/arbitrum/tokenlist.json, packages/app/public/assets/blockchains/ethereum/tokenlist.json, packages/app/public/assets/blockchains/gnosis/tokenlist.json
Improve token names to mirror what is defined on chain, so users can be confident on the token they are trading.
=> fix: improve token names

packages/app/components/OrdersProgressBar.tsx, packages/app/components/StacksTable.tsx, packages/app/components/stack-modal/StackProgress.tsx
**before**
**after**
- Show only orders that were executed 
- show full bar
=> show complete bar on orders when all funds are used

.github/workflows/CI.yml, packages/app/components/stack-modal/StackFrequencyAndDates.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stack-modal/StackOrdersProgress.tsx, packages/app/components/stack-modal/StackOrdersTable.tsx, packages/app/components/stackbox/ConfirmStackModal.tsx, packages/app/utils/token.ts
**Summary** 
- Simplify text on Confirm Modal
- Refactor StackModal code
- Simplify orders table column on mobile
**Problem**
**Now**
Also orders table on mobile now show "tx" and less numbers on the address.
=> Simplify confirm stack

packages/app/components/StacksTable.tsx, packages/app/components/stack-modal/StackFrequencyAndDates.tsx, packages/app/models/order/order.ts
* [STK-255](https://linear.app/swaprhq/issue/STK-255/my-stacks-breaks-for-some-one-time-orders)
* [STK-257](https://linear.app/swaprhq/issue/STK-257/order-details-display-wrong-start-and-end-dates)
* Adds different checks when we have a stack with no `orderSlots`.
https://www.loom.com/share/6522431e773f4350af5ce0b70c93f909?sid=1fd75bc2-f862-4aa8-bf96-61e762dc12f5
=> [STK-255][FIX] - My Stacks breaks for some one time orders

packages/app/components/stackbox/Stackbox.tsx
* Updates the start time on the stack confirmation modal if the start time is equal to or less than 10 minutes in the future.
https://www.loom.com/share/434fe59f8a3a4019874864c2c29fb64b?sid=2731eb81-3b8e-4acd-8865-c5bd6ffcaa88
=> [STK-249][FIX] - Stackbox start date fails TX creation

packages/app/components/stack-modal/StackFrequencyAndDates.tsx, packages/app/models/stack-order/stack-order.ts
* Uses the "Start Date" to compute the "Next Order" date for no-slots stacks.
* Returns 0 if there's no executed buy amount for an order (this may happen if the order expires, for example)
=> [STK-253][FIX] - My Stacks displaying NaN

packages/app/components/stackbox/Stackbox.tsx
* Hides the Stackbox stack details tile if the selected end date is equal to or less than the selected start date
=> [STK-251][FIX] - Stackbox details texts misbehavior

packages/app/contexts/TokenListContext.tsx
Long story short: I couldn't find why some of our context chainId changes do not trigger the effect that fetches the balances for a connected wallet. The chainId value changes correctly, but this doesn't trigger the effect sometimes.
Some of the reasons for a value change in the effect dependency array not triggering the effect execution:
* React makes a shallow comparison on values, meaning, if the value reference in memory does not change, then it won't trigger the effect (for example mutating an array or an object)
* Values outside the React state sometimes do not trigger effects
So, all-in-all, values present in the dependency array do not guarantee the effect to trigger when these change. If there are other reasons for this to happen (most likely there are) I couldn't find them.
I …
=> [STK-247][FIX] - Network switching bug

packages/app/components/OrdersProgressBar.tsx, packages/app/models/stack-order/stack-order.ts
* Updates the computations we do to set the progress bar, we were taking the executed orders as the total orders.
=> [STK-258][FIX] - Bar showing complete on the first order 

packages/app/models/stack-order/stack-order.ts
* Updates our checks for stack remaining funds, we had an edge-case bug where if the stack only spent our protocol fee and the stack completed without spending any more funds, we didn't allow the user to withdraw the remaining unspent funds.
https://www.loom.com/share/0dbc2f9189104fa9a64e65bb2858927b?sid=fb70b53a-b4d4-4c43-868d-c0d31eb50047
=> [STK-215][FIX] - Completed stack with funds without showing "withdraw" button

packages/app/components/stackbox/Stackbox.tsx
* Updates amount input pattern and allows decimal values
=> [STK-217][FIX] - Input on mobile unable to use decimals

packages/sdk/src/vaults/constants.ts
With this change we will be able to update our subgraph API endpoint URLs for the three supported chains, this way we will be able not to consume API credits for our development.
* Creates env vars to handle our subgraph API endpoints
=> [FEAT] - Creates env vars to handle our subgraph API endpoints

packages/app/app/not-found.tsx, packages/app/app/stacks/empty-state.tsx, packages/app/app/stacks/page.tsx, packages/app/app/stacks/stacksOrders.tsx, packages/app/components/SelectNetwork.tsx, packages/app/components/navbar/MobileMenu.tsx, packages/app/components/navbar/Navbar.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/constants/index.ts, packages/app/constants/pathnames.ts, packages/app/ui/buttons/ButtonLink.tsx
This seems to be the same issue described in our previous issue for a bug in our network switch handling. For more context, please see: https://github.com/SwaprHQ/stackly-ui/pull/194
* Persists the chain ID in the search params
* Resets the stackbox values only if we're changing chains in the landing page
=> [STK-256][FIX] - My Stacks not updating correctly

packages/app/components/SelectNetwork.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/contexts/NetworkContext.tsx
* Removes an unneeded search param reset from our Network Context.
* Removes an unwanted search params chain ID reset that was colliding with WAGMI's chain ID
=> [FIX][STK-259] -No image in Stackbox token icons

packages/app/app/stacks/stacksOrders.tsx
* *NOTE:* As I couldn't reproduce the CoW API failure locally, I can't provide visual evidence for this fix, but I think it should cover the use case where the CoW API fails to get Stacks data
* Adds a safety check to cover CoW API failing to get the stack orders
=> [FIX][STK-261] - App breaks when the CoW API fails to fetch Stacks data
