SwaprHQ/stackly-ui

packages/app/app/layout.tsx, packages/app/tailwind.config.js
This PR does the initial setup of tailwind config.
Also adds the background color and font family of the root layout.
=> feat: setup tailwind theme 

packages/app/app/ui/page.tsx, packages/app/package.json, packages/app/ui/buttons/ChipButton.tsx, packages/app/ui/buttons/RadioButton.tsx, packages/app/ui/buttons/index.ts, yarn.lock
This PR adds the new ChipButton and RadioButton UI elements.
Both components are present in UI page.
=> feat: create ChipButton element

.gitignore, packages/subgraph/.eslintrc, packages/subgraph/abis/DCAOrder.json, packages/subgraph/abis/ERC20.json, packages/subgraph/abis/OrderFactory.json, packages/subgraph/bin/build-subgraph.ts, packages/subgraph/bin/config.ts, packages/subgraph/package.json, packages/subgraph/schema.graphql, packages/subgraph/src/mappings/factory.ts, packages/subgraph/src/mappings/order.ts, yarn.lock
This PR copies the `subgraph` repo into this project.
=> chore: move subgraph package to this repo

packages/app/next.config.js
Fixes deploy on fleek and IPFS.
=> fix: deploy on fleek

.github/workflows/CI.yml, packages/app/components/StackedTokenLogoPair.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stack-modal/StackProgress.tsx, packages/app/package.json, packages/sdk/src/vaults/subgraph.ts, yarn.lock
- Updates sdk subgraph order type
- Removes typescript no check comment
- Fix CI by changing commands order (first build, then typecheck)
=> fix: update sdk subgraph order type

packages/app/app/ui/page.tsx, packages/app/components/StacksTable.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/contexts/ModalContext.tsx
**Description**
- Update `ModalContext` to support multiple modals open
- Update components to use new api
_Removed Toast for now from `ModalsContext` based on @ElRodrigote it shouldn't be here, we can leave it open for now as it's not added to the flow yet._
=> feat: Add support for multiple modals open

packages/app/providers/wagmi-config.ts
**description**
this PR removes the option to switch to ethereum network
=> fix: remove mainnet network till we deploy our contracts

packages/app/components/token-picker/TokenPicker.tsx
**description**
- add full width to `TokenListRow`
- add proper height to `TokenListRow`
comments: https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez
**before**
**after**
=> design fix: add full width and proper height to TokenListRow (Token Picker)

packages/app/components/StacksTable.tsx, packages/app/components/stack-modal/StackModal.tsx, packages/app/utils/datetime.ts
=> fix: show cancelled date on progress on cancelled stacks

packages/app/app/layout.tsx, packages/app/components/stackbox/Stackbox.tsx
**design review**
comments: https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez
=> fix: divider should be full length on stackbox

packages/app/ui/buttons/RadioButton.tsx, packages/app/ui/buttons/base.ts
comments: https://web.ruttl.com/share/gWnw47S1jJZvzZcB4eez
=> fix: outline stroke on radio buttons should be lighter

packages/app/components/DatePicker.tsx, packages/app/components/SelectNetwork.tsx
=> fix: network switcher over overlay

packages/app/app/layout.tsx, packages/app/components/DatePicker.tsx, packages/app/components/navbar/MobileMenu.tsx, packages/app/components/navbar/Navbar.tsx, packages/app/ui/dialog/Dialog.tsx
fixes:
- move padding to layout 
- icon was overlaping menu on mobile
=> update: move page padding to layout

packages/app/app/stacks/empty-state.tsx, packages/app/app/stacks/no-wallet-state.tsx, packages/app/app/stacks/stacksOrders.tsx, packages/app/app/ui/page.tsx, packages/app/components/ConnectButton.tsx, packages/app/components/SelectNetwork.tsx, packages/app/components/StacksTable.tsx, packages/app/components/stackbox/ConfirmStackModal.tsx, packages/app/components/stackbox/Stackbox.tsx, packages/app/ui/buttons/base.ts, packages/app/ui/dialog/DialogFooterActions.tsx
Update Buttons to match design. 
- same size
- styles
- etc
=> update: Button styles

packages/app/app/mint/page.tsx, packages/app/components/BetaNFTModal.tsx
Create mint page without contract logic. Mint NFT section has different spacing from figma.
=> feat: create mint page

packages/app/app/mint/page.tsx, packages/app/contexts/ModalContext.tsx, packages/app/package.json, yarn.lock
Mint firework effect after minting NFT.
https://github.com/SwaprHQ/stackly-ui/assets/23079677/5bdd80c5-0ef8-446c-945c-206b990a34e9
=> feat: mint firework effect

packages/app/components/stack-modal/StackModal.tsx, packages/app/components/stackbox/Stackbox.tsx
stack now" to "confirm stack" as it will open the confirm modal
also change "Cancel stacking" → "cancel stack"
=> update: improve buttons text

packages/app/contexts/TokenListContext.tsx
This PR adds multiple token lists per chain, making it easier to have more tokens per chain. Also adds CoW Swap lists to the token list.
=> feat: add multiple token lists per chain

packages/landing/app/page.tsx
=> landing: add DCA section

packages/landing/app/page.tsx, packages/landing/components/QAndAAccordion/QAndAAccordion.tsx, packages/landing/components/QAndAAccordion/index.ts, packages/landing/public/assets/icons/caret-up.svg, packages/landing/public/assets/icons/index.tsx, packages/landing/styles/global.css, packages/landing/ui/icon/Icon.tsx
=> landing: add FAQ section

packages/app/components/ConnectButton.tsx, packages/app/hooks/autoConnect.ts, packages/app/hooks/index.ts, packages/app/next.config.js, packages/app/providers/wagmi-config.ts, packages/app/public/manifest.json
PR adds logic and manifest.json so Stackly can be used as a Safe App. 
Follow this tutorial to create a custom app using the preview link https://help.safe.global/en/articles/40859-add-a-custom-safe-app .
=> feat[STK-3]: add Stackly as a safe app

packages/landing/app/page.tsx, packages/landing/components/TryStacklyBanner/TryStacklyBanner.tsx, packages/landing/ui/buttons/base.ts, packages/landing/ui/text/DisplayText.tsx
- better display text on mobile
- add missing pontuaction
- Try Stackly banner
- fix image overlapping button
=> landing: improve responsivess and copy

packages/app/components/stackbox/Stackbox.tsx, packages/app/utils/constants.ts
=> feat: set wxdai and weth as default selected tokens

packages/app/components/stackbox/Stackbox.tsx
**Summary**
swap from <-> to tokens when clicking arrow icon
=> feat: swap from <-> to tokens when clicking stackbox arrow icon

packages/app/components/stackbox/Stackbox.tsx
=> Update:  Add ellipsis to token amount input

.github/workflows/CI.yml, .yarnrc.yml, package.json
* Update `build` command to generate SDK package needed files.
2) In the root folder:
* `bun run clean:deep` to remove all the Git ignored files and directories
* Run `bun install` to get all the project dependencies
* Run `bun run build` to build all the packages in the monorepo
=> [SWA-210][INFRA] - Update pipelines and monorepo build process

package.json
This script is meant for setup the app.
For eg, when cloning to start working, just need to run: 
`npm run setup`
=> add script for setup

packages/app/app/stacks/stacksOrders.tsx, packages/app/components/EmptyState.tsx, packages/app/components/index.ts, packages/app/components/token-picker/TokenPicker.tsx, packages/app/contexts/TokenListContext.tsx
- Adds custom token logic to Token Picker. 
- Made some changes to Token Picker logic.
=> feat: add custom token logic

packages/landing/app/page.tsx, packages/landing/components/sections/HeroBanner/HeroBanner.tsx
=> Improve hero text

packages/sdk/src/vaults/constants.ts
Updates subgraph endpoints to decentralised network
=> feat: update subgraph endpoints

packages/app/components/stackbox/Stackbox.tsx
* Updates the past end date error when the end date changes
https://www.loom.com/share/ebd9627fbbea4e85824709363221214f?sid=0ff13068-b1f0-4c05-93dd-601640c619bd
=> [STK-250][FIX] - fix: update the past end date error on date change

package.json
Version bumping our package to merge into `main`
=> release v1.3.2

packages/app/contexts/StackboxFormContext.tsx
* Updates our Stackbox form context types for values coming from `next-usequerystate`
=> [CHORE][STK-214] - Improve stackbox form state typing

package.json
Version bumping our package to merge into `main`
=> version bump v1.3.5
